# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and test ( iOS 15.0)
      run: xcode-select -p
    - name: os name
      run: sw_vers
    - name: Run on simulator
      run: xcrun simctl list
#xcodebuild EventBus -scheme EventBus -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 14 Pro'
 
