# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #the only job in the list, named `build`
  build: 
    #specify OS to run the jobs on
    runs-on: macos-latest 
 strategy:
      matrix:
        os: [macos-14.6]
    
    steps: 
      # step 1, use Marketplace action called Checkout@v2, to checkout the code
    - uses: actions/checkout@v4 #'uses' keyword launches the Marketplace action
      # step 2, verbosely build the package using the `swift` CLI
    - name: Build
      run: swift build -v
