# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

# runs-on: macos-14 
strategy:
      matrix:
        # Full set of Firebase-Package tests only run on iOS. Run subset on other platforms.
        # visionOS isn't buildable from here (even with Firestore source) because the test
        # targets need Analytics.
        target: [macOS]
        os: [macos-14]
        include:
          - os: macos-14
            xcode: Xcode_16
          - os: macos-14
            xcode: Xcode_15.3
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    # Sanity check to make sure we use a valid device in the next step
    - name: List available devices
      run: xcrun simctl list devicetypes 
    #generic/platform=iOS is sufficient for just building, - but need to specify concrete destination for tests
    - name: Build and run tests
      run: xcodebuild test -scheme EventBus -destination 'platform=iOS Simulator,name=iPhone 17 Pro' #or any other name from the list of sim devices
    
