name: Build and Lint

on:
  push:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SwiftLint
        run: |
          # Install SwiftLint
          brew install swiftlint

          # Run SwiftLint
          swiftlint lint

      - name: Build Package
        run: swift build
